/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitask;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP
 */
public class HospitalManagementSystem extends javax.swing.JFrame {

    /**
     * Creates new form HospitalManagementSystem
     */
    public HospitalManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        record_btn = new javax.swing.JButton();
        registration_btn = new javax.swing.JButton();
        appointment_btn = new javax.swing.JButton();
        ehr_btn = new javax.swing.JButton();
        payment_btn = new javax.swing.JButton();
        inventory_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME GUEST!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 380, 80));

        record_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        record_btn.setText("Records");
        record_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_btnActionPerformed(evt);
            }
        });
        getContentPane().add(record_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 740, 280, 70));

        registration_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        registration_btn.setText("Registration");
        registration_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registration_btnActionPerformed(evt);
            }
        });
        getContentPane().add(registration_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 240, 370, 70));

        appointment_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        appointment_btn.setText("Appointment Scheduling");
        appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointment_btnActionPerformed(evt);
            }
        });
        getContentPane().add(appointment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 340, 370, 70));

        ehr_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ehr_btn.setText("Electronic Health Record(EHR)");
        ehr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ehr_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ehr_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 440, 440, 70));

        payment_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        payment_btn.setText("Payment");
        payment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_btnActionPerformed(evt);
            }
        });
        getContentPane().add(payment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 540, 310, 70));

        inventory_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        inventory_btn.setText("Inventory Management");
        inventory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_btnActionPerformed(evt);
            }
        });
        getContentPane().add(inventory_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 640, 370, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\hospitalimagefinal.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void record_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_btnActionPerformed
       new DatabaseFrame().show();
       dispose();
    }//GEN-LAST:event_record_btnActionPerformed

    private void inventory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_btnActionPerformed
       new InventoryManagementFrame().show();
       dispose();
    }//GEN-LAST:event_inventory_btnActionPerformed

    private void registration_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registration_btnActionPerformed
      new Registration().show();
      dispose();
    }//GEN-LAST:event_registration_btnActionPerformed

    private void appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointment_btnActionPerformed
       new Appointment().show();
       dispose();
    }//GEN-LAST:event_appointment_btnActionPerformed

    private void ehr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ehr_btnActionPerformed
       new EHRFrame().show();
       dispose();
    }//GEN-LAST:event_ehr_btnActionPerformed

    private void payment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_btnActionPerformed
        new PaymentFrame().show();
        dispose();
    }//GEN-LAST:event_payment_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalManagementSystem().setVisible(true);
            }
        });
         try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                
                 }
                catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e)
                {
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointment_btn;
    private javax.swing.JButton ehr_btn;
    private javax.swing.JButton inventory_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton payment_btn;
    private javax.swing.JButton record_btn;
    private javax.swing.JButton registration_btn;
    // End of variables declaration//GEN-END:variables
}
