/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitask;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP
 */
public class InventoryManagementFrame extends javax.swing.JFrame {

   static Connection con = null;
    static Connection con1 = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public InventoryManagementFrame() {
        initComponents();
        jPanel1.setBackground(new Color(250,250,250,100));
        con = DatabaseConnection.getConnection();
        con1 = DatabaseConnection.getConnection();
        
        role_combo.addItem("Select your role");
        role_combo.addItem("Administrator");
        role_combo.addItem("Inventory manager");
        role_combo.addItem("Pharmacist");
        role_combo.addItem("Doctor/Staff");
        role_combo.addItem("Receptionist");
        role_combo.addItem("Guest/visitor");
        
        
        category_combo.addItem("Select category of the Item");
        category_combo.addItem("Medical Supplies");
        category_combo.addItem("Pharmaceuticals");
        category_combo.addItem("Surgical Instruments");
        category_combo.addItem("Diagnostic Equipment");
        category_combo.addItem("Laboratory Supplies");
        category_combo.addItem("Personal Protective Equipment(PPE)");
        category_combo.addItem("Patient Care Equipment");
        category_combo.addItem("Cleaning And Sanitation Supplies");
        category_combo.addItem("IT Equipment");
        category_combo.addItem("Emergency And First Aid Supplies");
       category_combo.addItem("Radiology Supplies");
       
        item_name_combo.addItem("Select the Item");
      
        storage_combo.addItem("Select storage location of the Item");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantity_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        supplier_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        batch_number_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        expiry_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        storage_combo = new javax.swing.JComboBox<>();
        role_combo = new javax.swing.JComboBox<>();
        category_combo = new javax.swing.JComboBox<>();
        item_name_combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setText("Inventory Management");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\homefinal.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("User Role:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Category of Item:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Item Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Quantity:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Storage Location:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Supplier:");

        supplier_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_txtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Batch Number:");

        batch_number_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batch_number_txtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Expiry Date:");

        expiry_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiry_txtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Price:");

        price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_txtActionPerformed(evt);
            }
        });

        save_btn.setText("Save Record");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        role_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_comboActionPerformed(evt);
            }
        });

        category_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(role_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(item_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(batch_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(expiry_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(storage_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(supplier_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(241, 241, 241))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(role_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storage_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplier_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batch_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiry_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_btn)
                    .addComponent(update_btn)
                    .addComponent(clear_btn)
                    .addComponent(search_btn))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 770, 840));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\stetoscopefinal.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplier_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplier_txtActionPerformed

    private void batch_number_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batch_number_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batch_number_txtActionPerformed

    private void expiry_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiry_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiry_txtActionPerformed

    private void price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_txtActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
if(name_txt.getText().equals(""))
           JOptionPane.showMessageDialog(null,"Name is mandetory");
        else if(role_combo.getSelectedItem().toString().equals("Select your role"))
           JOptionPane.showMessageDialog(null,"Select your role");
        else if(category_combo.getSelectedItem().toString().equals("Select category of the Item"))
           JOptionPane.showMessageDialog(null,"Enter the category of item");
            else if(item_name_combo.getSelectedItem().toString().equals("Select the Item"))
           JOptionPane.showMessageDialog(null,"Select the Item");
             else if(quantity_txt.getText().equals(""))
           JOptionPane.showMessageDialog(null,"Enter quantity of the item");
             else if(storage_combo.getSelectedItem().toString().equals("Select storage location of the Item"))
           JOptionPane.showMessageDialog(null,"Select storage location of the item");
             else if(supplier_txt.getText().equals(""))
           JOptionPane.showMessageDialog(null,"Enter supplier of the item");
             else if(batch_number_txt.getText().equals(""))
           JOptionPane.showMessageDialog(null,"Batch number is mandetory");
          else if(expiry_txt.getText().equals(""))
           JOptionPane.showMessageDialog(null," Expiry date is mandetory");
        else if(price_txt.getText().equals(""))
           JOptionPane.showMessageDialog(null,"Enter price of the item");
       else
            JOptionPane.showMessageDialog(null,"Data saved successfully!!");
       
       
       try{
           String sql = "insert into inventory_management_table values (?,?,?,?,?,?,?,?,?,?)";
           pst = con.prepareStatement(sql);
           
              pst.setString(1, name_txt.getText());
           String user;
           user = role_combo.getSelectedItem().toString();
           pst.setString(2,user);
          
           String category;
           category = category_combo.getSelectedItem().toString();
           pst.setString(3, category);
           
           String item;
           item = item_name_combo.getSelectedItem().toString();
           pst.setString(4, item);
           pst.setInt(5, Integer.parseInt(quantity_txt.getText()));
           
           String storage;
           storage = storage_combo.getSelectedItem().toString();
           pst.setString(6, storage);
            pst.setString(7, supplier_txt.getText());
             pst.setString(8,batch_number_txt.getText());
              pst.setString(9,expiry_txt.getText());
               pst.setInt(10, Integer.parseInt(price_txt.getText()));
               
               pst.executeUpdate();
               con.close();
               
       }
       catch(NumberFormatException | SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
        
    }//GEN-LAST:event_save_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
      try {
    String sql = "UPDATE inventory_management_table SET user_role = ?, category = ?, item_name = ?, quantity = ?, storage_location = ?, "
               + "supplier = ?, batch_number = ?, expiry_date = ?, price = ? WHERE user_name = ?";
    pst = con.prepareStatement(sql);

    String user = role_combo.getSelectedItem().toString();
    pst.setString(1, user);
    
    String category = category_combo.getSelectedItem().toString();
    pst.setString(2, category);
    
    String item = item_name_combo.getSelectedItem().toString();
    pst.setString(3, item);
    
    pst.setInt(4, Integer.parseInt(quantity_txt.getText()));
    
    String storage = storage_combo.getSelectedItem().toString();
    pst.setString(5, storage);
    
    pst.setString(6, supplier_txt.getText());
    pst.setString(7, batch_number_txt.getText());
    pst.setString(8, expiry_txt.getText());
    
    pst.setInt(9, Integer.parseInt(price_txt.getText()));
    pst.setString(10, name_txt.getText());
    
    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Record updated successfully!!");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
    e.printStackTrace();
} finally {
    try {
        if (pst != null) pst.close();
        if (con != null) con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
      }
    }//GEN-LAST:event_update_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        role_combo.setSelectedItem("Select your role");
        name_txt.setText("");
        item_name_combo.setSelectedItem("Select the Item");
        category_combo.setSelectedItem("Select category of the Item");
        quantity_txt.setText("");
        storage_combo.setSelectedItem("Select storage location of the Item");
        supplier_txt.setText("");
        batch_number_txt.setText("");
        expiry_txt.setText("");
        price_txt.setText("");
        save_btn.setEnabled(false);
       
    }//GEN-LAST:event_clear_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
       try{
           String sql1 = "select * from  inventory_management_table where user_name = ? ";
           pst = con1.prepareStatement(sql1);
           pst.setString(1,name_txt.getText());
           rs = pst.executeQuery();
           
           if(rs.next())
           {
               role_combo.setSelectedItem(rs.getString("user_role"));
                category_combo.setSelectedItem(rs.getString("category"));
                item_name_combo.setSelectedItem(rs.getString("item_name"));
                quantity_txt.setText(rs.getString("quantity"));
                storage_combo.setSelectedItem(rs.getString("storage_location"));
                supplier_txt.setText(rs.getString("supplier"));
                batch_number_txt.setText(rs.getString("batch_number"));
                expiry_txt.setText(rs.getString("expiry_date"));
               price_txt.setText(rs.getString("price"));
           }
            else
            {
                JOptionPane.showMessageDialog(null,"Record not found!!");
            }
               con1.close();
           
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_search_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HospitalManagementSystem().show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void role_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_comboActionPerformed
       if(role_combo.getSelectedItem().toString().equals("Doctor/Staff") || role_combo.getSelectedItem().toString().equals("Receptionist") || role_combo.getSelectedItem().toString().equals("Guest/visitor")){
            save_btn.setEnabled(false);
            update_btn.setEnabled(false);}
        else{
            save_btn.setEnabled(true);
            update_btn.setEnabled(true);
        }
    }//GEN-LAST:event_role_comboActionPerformed

    private void category_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_comboActionPerformed

        String selecteditem = category_combo.getSelectedItem().toString();
      
        if("Medical Supplies".equals(selecteditem))
        {
            item_name_combo.removeAllItems();
            item_name_combo.addItem("Select the Item");
             item_name_combo.addItem("Syringes");
             item_name_combo.addItem("Gloves");
             item_name_combo.addItem("Bandages");
             item_name_combo.addItem("Gauze Pads");
             item_name_combo.addItem("Sterilization Wraps");
             item_name_combo.addItem("Surgical Drapse");
             
             storage_combo.removeAllItems();
             storage_combo.addItem("Select storage location of the Item");
             storage_combo.addItem("Central Supply Room");
             storage_combo.addItem("Operating Room Storage");
             storage_combo.addItem("Nursing Stations");
        }
        else if("Pharmaceuticals".equals(selecteditem)){
            item_name_combo.removeAllItems();
            item_name_combo.addItem("Select the Item");
            item_name_combo.addItem("Antibiotics");
             item_name_combo.addItem("Pain Relievers");
              item_name_combo.addItem("Antiseptics");
               item_name_combo.addItem("Vaccines");
              item_name_combo.addItem("IV Fluids");
               item_name_combo.addItem("Insulin");
                item_name_combo.addItem("Anesthetics");
                 
                storage_combo.removeAllItems();
                storage_combo.addItem("Pharmacy Storage Room");
                storage_combo.addItem("Medication Carts");
                storage_combo.addItem("Controlled Substances Vault");
                storage_combo.addItem("Refrigeration Units");
        }
        else if("Surgical Instruments".equals(selecteditem)){
            item_name_combo.removeAllItems();
            item_name_combo.addItem("Select the Item");
            item_name_combo.addItem("Scalpels");
            item_name_combo.addItem("Forceps");
            item_name_combo.addItem("Scissors");
            item_name_combo.addItem("Retractors");
            item_name_combo.addItem("Needle Holders");
            item_name_combo.addItem("Surgical Clamps");
            
             storage_combo.removeAllItems();
                storage_combo.addItem("Sterile Storage Area");
                storage_combo.addItem("Operating Room Cabinets");
                storage_combo.addItem("Instrument Trays");
        }
         
        else if("Diagnostic Equipment".equals(selecteditem)){
            item_name_combo.removeAllItems();
             item_name_combo.addItem("Select the Item");
              item_name_combo.addItem("Blood Pressure Monitors");
               item_name_combo.addItem("Stethoscopes");
                item_name_combo.addItem("Thermometers");
                item_name_combo.addItem("Glucometers");
                item_name_combo.addItem("ECG Machines");
              item_name_combo.addItem("Pulse Oximeters");
               item_name_combo.addItem("Ultrasound Machines");
                item_name_combo.addItem("X-ray Machines");
                
                 storage_combo.removeAllItems();
                storage_combo.addItem("Diagnostic Lab");
                storage_combo.addItem("Radiology Department");
                storage_combo.addItem("Emergency Room");
                storage_combo.addItem("Portable Equipmqnt Storage");
        }
         else if("Laboratory Supplies".equals(selecteditem)){
            item_name_combo.removeAllItems();
             item_name_combo.addItem("Select the Item");
             item_name_combo.addItem("Test Tubes");
             item_name_combo.addItem("Petri Dishes");
             item_name_combo.addItem("Microscope Slides");
             item_name_combo.addItem("Reagents");
             item_name_combo.addItem("Pipettes");
             item_name_combo.addItem("Centrifuge");
             
              storage_combo.removeAllItems();
                storage_combo.addItem("Laboratory Storage Cabinets");
                storage_combo.addItem("Refrigerated Storage");
                storage_combo.addItem("Chemical Storage");
         }
         else if("Personal Protective Equipment(PPE)".equals(selecteditem)){
            item_name_combo.removeAllItems();
             item_name_combo.addItem("Select the Item");
             item_name_combo.addItem("Surgical Masks");
             item_name_combo.addItem("N95 Respirators");
             item_name_combo.addItem("Face Shields");
             item_name_combo.addItem("Gowns");
             item_name_combo.addItem("Protective Eyewear");
             item_name_combo.addItem("Hand Sanitizers");
             
              storage_combo.removeAllItems();
                storage_combo.addItem("Supply Room");
                storage_combo.addItem("Nursing Stations");
                storage_combo.addItem("Emergency Response Carts");
         }
         else if("Patient Care Equipment".equals(selecteditem)){
            item_name_combo.removeAllItems();
           item_name_combo.addItem("Select the Item");
           item_name_combo.addItem("Hospital Beds");
           item_name_combo.addItem("Wheelchairs");
           item_name_combo.addItem("IV Stands");
           item_name_combo.addItem("Bedpans");
           item_name_combo.addItem("Patient Lifts");
           item_name_combo.addItem("Oxygen Concentrators");
           
            storage_combo.removeAllItems();
                storage_combo.addItem("Equipment Storage Room");
                storage_combo.addItem("Patient Rooms");
                storage_combo.addItem("Nursing Stations");
                storage_combo.addItem("Supply Closets");
         }
          else if("Cleaning And Sanitation Supplies".equals(selecteditem)){
            item_name_combo.removeAllItems();
           item_name_combo.addItem("Select the Item");
            item_name_combo.addItem("Disinfectants");
           item_name_combo.addItem("Bleach");
           item_name_combo.addItem("Cleaning Agents");
           item_name_combo.addItem("Gloves");
           item_name_combo.addItem("Air Fresheners");
           item_name_combo.addItem("Waste Disposal Bags");
           
            storage_combo.removeAllItems();
                storage_combo.addItem("Janitorial Closets");
                storage_combo.addItem("Housekeeping Department Storage");
                storage_combo.addItem("Utility Rooms");
        }
        else if("IT Equipment".equals(selecteditem)){
            item_name_combo.removeAllItems();
           item_name_combo.addItem("Select the Item");
           item_name_combo.addItem("Desktop Computers");
           item_name_combo.addItem("Laptops");
           item_name_combo.addItem("Servers");
           item_name_combo.addItem("Printers");
           item_name_combo.addItem("Barcode Scanners");
           item_name_combo.addItem("Networking Devices");
           item_name_combo.addItem("Data Storage Devices");
           
            storage_combo.removeAllItems();
                storage_combo.addItem("IT Department Storage");
                storage_combo.addItem("Server Rooms");
                storage_combo.addItem("Office Storage Cabinets");
        }
         else if("Emergency And First Aid Supplies".equals(selecteditem)){
            item_name_combo.removeAllItems();
           item_name_combo.addItem("Select the Item");
            item_name_combo.addItem("First Aid Kits");
           item_name_combo.addItem("Defibrillators");
           item_name_combo.addItem("Oxygen Tanks");
           item_name_combo.addItem("Splints");
           item_name_combo.addItem("Burn Kits");
           item_name_combo.addItem("Emergency Blankets");
           item_name_combo.addItem("Emergency Stretchers");
           
            storage_combo.removeAllItems();
                storage_combo.addItem("Emergency Room");
                storage_combo.addItem("First Aid Stations");
                storage_combo.addItem("Ambulances");
                storage_combo.addItem("Emergency Supply Cabinets");
        }
         else if("Radiology Supplies".equals(selecteditem)){
            item_name_combo.removeAllItems();
           item_name_combo.addItem("Select the Item");
            item_name_combo.addItem("X-ray Films");
           item_name_combo.addItem("Contrast Agents");
           item_name_combo.addItem("Lead Aprons");
           item_name_combo.addItem("Thyroid Shields");
           item_name_combo.addItem("Positioning Sponges");
           item_name_combo.addItem("Radiation Badges");
           item_name_combo.addItem("Image Markers");
           
           storage_combo.removeAllItems();
                storage_combo.addItem("Radiology Department");
                storage_combo.addItem("Film Storage");
                storage_combo.addItem("Lead-lined Cabinets");
                storage_combo.addItem("Darkrooms");
        }
    }//GEN-LAST:event_category_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManagementFrame().setVisible(true);
            }
        });
         try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                
                 }
                catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e)
                {
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batch_number_txt;
    private javax.swing.JComboBox<String> category_combo;
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField expiry_txt;
    private javax.swing.JComboBox<String> item_name_combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JComboBox<String> role_combo;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JComboBox<String> storage_combo;
    private javax.swing.JTextField supplier_txt;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
