/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitask;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP
 */
public class PaymentFrame extends javax.swing.JFrame {

  static Connection con = null;
       static Connection con1 = null;
        static Connection con2 = null;
      static Connection searchcon = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
   

    public PaymentFrame() {
        initComponents();
        
        con = DatabaseConnection.getConnection();
        searchcon = DatabaseConnection.getConnection();
        con1 = DatabaseConnection.getConnection();
        con2 = DatabaseConnection.getConnection();
             payment_enroll_panel.setBackground(new Color(250,250,250,100));
             payment_process_panel.setBackground(new Color(250,250,250,100));
             qrscanner_panel.setBackground(new Color(250,250,250,100));
               payment_process_panel.setBackground(new Color(250,250,250,100));
             
        payment_status_combo.addItem("select payment status");
         payment_status_combo.addItem("Paid");
          payment_status_combo.addItem("Half paid");
           payment_status_combo.addItem("EMI transfer");
            payment_status_combo.addItem("Pending");
            
             payment_method_combo.addItem("select payment method");
            payment_method_combo.addItem("Cash");
             payment_method_combo.addItem("Creditcard/Debit card");
              payment_method_combo.addItem("Cheque/DD payment");
               payment_method_combo.addItem("UPI(unified payments interface)");
          
               
               payment_btn.setEnabled(false);
               qr_label.setEnabled(false);
               pay_btn.setEnabled(false);
               
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        payment_panel = new javax.swing.JTabbedPane();
        payment_enroll_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        patient_id_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        patient_name_txt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        total_amount_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        submitted_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        service_textarea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        payment_method_combo = new javax.swing.JComboBox<>();
        payment_status_combo = new javax.swing.JComboBox<>();
        back_btn = new javax.swing.JButton();
        payment_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        payment_process_panel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        payment_process_home_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        card_number_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        security_code_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        month_txt = new javax.swing.JTextField();
        day_txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        robot_checkbox = new javax.swing.JCheckBox();
        pay_btn = new javax.swing.JButton();
        payment_process_back_btn = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        qrscanner_panel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        qr_home_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        qr_label = new javax.swing.JLabel();
        qr_pay_btn = new javax.swing.JButton();
        qr_back_btn = new javax.swing.JButton();
        paytm_rbtn = new javax.swing.JRadioButton();
        phonepe_rbtn = new javax.swing.JRadioButton();
        gpay_rbtn = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        bhim_rbtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Payment!");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\homefinal.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Patient ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Patient Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Service Description:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Total Amount:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Submitted Amount:");

        service_textarea.setColumns(20);
        service_textarea.setRows(5);
        jScrollPane1.setViewportView(service_textarea);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("(If Applicable)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Payment Status:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Payment Method:");

        payment_method_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_method_comboActionPerformed(evt);
            }
        });

        payment_status_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_status_comboActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        payment_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        payment_btn.setText("Processed to Payment");
        payment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_btnActionPerformed(evt);
            }
        });

        search_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payment_enroll_panelLayout = new javax.swing.GroupLayout(payment_enroll_panel);
        payment_enroll_panel.setLayout(payment_enroll_panelLayout);
        payment_enroll_panelLayout.setHorizontalGroup(
            payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addComponent(jSeparator1)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(payment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                        .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(patient_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(patient_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(submitted_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payment_enroll_panelLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(total_amount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(payment_status_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(payment_method_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
        );
        payment_enroll_panelLayout.setVerticalGroup(
            payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patient_id_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patient_name_txt)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payment_enroll_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total_amount_txt)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitted_txt)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payment_status_combo)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payment_method_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(payment_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        payment_panel.addTab("Enroll", payment_enroll_panel);

        payment_process_home_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\homefinal.png")); // NOI18N
        payment_process_home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_process_home_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Payment!");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Name as per Card:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Card Number:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Security Code:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Last 3 digits on card reversed");
        jLabel16.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Expires on:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("/");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("DD");
        jLabel19.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("MM");
        jLabel20.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Phone Number:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("Email ID:");

        robot_checkbox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        robot_checkbox.setText("I'M Not a ROBOT");
        robot_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robot_checkboxActionPerformed(evt);
            }
        });

        pay_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pay_btn.setText("Pay");
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });

        payment_process_back_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        payment_process_back_btn.setText("Back");
        payment_process_back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_process_back_btnActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payment_process_panelLayout = new javax.swing.GroupLayout(payment_process_panel);
        payment_process_panel.setLayout(payment_process_panelLayout);
        payment_process_panelLayout.setHorizontalGroup(
            payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payment_process_panelLayout.createSequentialGroup()
                .addComponent(payment_process_home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addComponent(jSeparator3)
            .addGroup(payment_process_panelLayout.createSequentialGroup()
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payment_process_panelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(payment_process_panelLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(security_code_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payment_process_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(card_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(payment_process_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(payment_process_panelLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(payment_process_panelLayout.createSequentialGroup()
                                        .addComponent(day_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(month_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92))
                                    .addGroup(payment_process_panelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107))))))
                    .addGroup(payment_process_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payment_process_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(payment_process_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(payment_process_panelLayout.createSequentialGroup()
                                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(payment_process_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(payment_process_panelLayout.createSequentialGroup()
                                        .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(payment_process_panelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(robot_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(payment_process_panelLayout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        payment_process_panelLayout.setVerticalGroup(
            payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payment_process_panelLayout.createSequentialGroup()
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payment_process_home_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(security_code_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(robot_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(payment_process_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payment_process_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        payment_panel.addTab("Payment Process", payment_process_panel);

        qr_home_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\homefinal.png")); // NOI18N
        qr_home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qr_home_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Payment!");

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel27.setText("Pay with..");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setText("Scan here to pay...");

        qr_label.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\qr image_large.jpg")); // NOI18N
        qr_label.setOpaque(true);

        qr_pay_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        qr_pay_btn.setText("Pay");
        qr_pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qr_pay_btnActionPerformed(evt);
            }
        });

        qr_back_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        qr_back_btn.setText("Back");
        qr_back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qr_back_btnActionPerformed(evt);
            }
        });

        paytm_rbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paytm_rbtn.setText("Paytm");
        paytm_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paytm_rbtnActionPerformed(evt);
            }
        });

        phonepe_rbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phonepe_rbtn.setText("PhonePe");
        phonepe_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonepe_rbtnActionPerformed(evt);
            }
        });

        gpay_rbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gpay_rbtn.setText("GPay");
        gpay_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpay_rbtnActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\gpay_final.png")); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\phonepe_final.png")); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\paytmimage_final.png")); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\bhimpay_final.png")); // NOI18N

        bhim_rbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bhim_rbtn.setText("BHIM Pay");
        bhim_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhim_rbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qrscanner_panelLayout = new javax.swing.GroupLayout(qrscanner_panel);
        qrscanner_panel.setLayout(qrscanner_panelLayout);
        qrscanner_panelLayout.setHorizontalGroup(
            qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qrscanner_panelLayout.createSequentialGroup()
                .addComponent(qr_home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addComponent(jSeparator2)
            .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(qrscanner_panelLayout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(qrscanner_panelLayout.createSequentialGroup()
                            .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(qrscanner_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bhim_rbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(qrscanner_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addGap(26, 26, 26)
                                    .addComponent(phonepe_rbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(qrscanner_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paytm_rbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(qrscanner_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(gpay_rbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qrscanner_panelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qr_pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79)))
                    .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(qr_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qrscanner_panelLayout.createSequentialGroup()
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21))
                        .addComponent(qr_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(101, 101, 101)))
        );
        qrscanner_panelLayout.setVerticalGroup(
            qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qrscanner_panelLayout.createSequentialGroup()
                .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qr_home_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(681, Short.MAX_VALUE))
            .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(qrscanner_panelLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(qrscanner_panelLayout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gpay_rbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phonepe_rbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paytm_rbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bhim_rbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40))
                        .addGroup(qrscanner_panelLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(qr_label)))
                    .addGap(83, 83, 83)
                    .addGroup(qrscanner_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qr_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qr_pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(126, 126, 126)))
        );

        payment_panel.addTab("QR Scanner", qrscanner_panel);

        getContentPane().add(payment_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 100, 790, 830));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\frame images\\stetoscopefinal.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qr_pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qr_pay_btnActionPerformed

        if(gpay_rbtn.isSelected())
        JOptionPane.showMessageDialog(null,"payment successfull!!");
        //qr_pay_btn.setEnabled(false);
        else if( phonepe_rbtn.isSelected())
        JOptionPane.showMessageDialog(null,"payment successfull!!");

        else if( paytm_rbtn.isSelected())
        JOptionPane.showMessageDialog(null,"payment successfull!!");
        else if(bhim_rbtn.isSelected())
        JOptionPane.showMessageDialog(null,"payment successfull!!");
        else
        {
            JOptionPane.showMessageDialog(null,"first select method of payment");
        }
    }//GEN-LAST:event_qr_pay_btnActionPerformed

    private void qr_back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qr_back_btnActionPerformed

        payment_panel.setSelectedIndex(0);

    }//GEN-LAST:event_qr_back_btnActionPerformed

    private void paytm_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paytm_rbtnActionPerformed

        if(paytm_rbtn.isSelected())
        qr_label.setEnabled(true);
        else
        qr_label.setEnabled(false);
    }//GEN-LAST:event_paytm_rbtnActionPerformed

    private void phonepe_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonepe_rbtnActionPerformed

        if(phonepe_rbtn.isSelected())
        qr_label.setEnabled(true);
        else
        qr_label.setEnabled(false);
    }//GEN-LAST:event_phonepe_rbtnActionPerformed

    private void gpay_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpay_rbtnActionPerformed
        if(gpay_rbtn.isSelected())
        qr_label.setEnabled(true);
        else
        qr_label.setEnabled(false);
    }//GEN-LAST:event_gpay_rbtnActionPerformed

    private void bhim_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhim_rbtnActionPerformed

        if(bhim_rbtn.isSelected())
        qr_label.setEnabled(true);
        else
        qr_label.setEnabled(false);
    }//GEN-LAST:event_bhim_rbtnActionPerformed

    private void qr_home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qr_home_btnActionPerformed
       new HospitalManagementSystem().show();
       dispose();
    }//GEN-LAST:event_qr_home_btnActionPerformed

    private void payment_method_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_method_comboActionPerformed

        if(payment_method_combo.getSelectedItem().toString().equals("Cash") || payment_method_combo.getSelectedItem().toString().equals("Cheque/DD payment"))
     {
         payment_btn.setEnabled(false);
          payment_panel.setEnabled(false);
     }
     else{
          payment_btn.setEnabled(true); 
      payment_panel.setEnabled(true);
     }
    }//GEN-LAST:event_payment_method_comboActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed

         try{
            String sql = "select * from payment_table where pat_id = ?";
            pst = con.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(patient_id_txt.getText()));
            rs = pst.executeQuery();
            
            if(rs.next())
            {
                patient_name_txt.setText(rs.getString("name"));
                service_textarea.setText(rs.getString("service_desc"));
                total_amount_txt.setText(rs.getString("total_amount"));
                 submitted_txt.setText(rs.getString("submitted_amount"));
                 payment_status_combo.setSelectedItem(rs.getString("payment_status"));
                 payment_method_combo.setSelectedItem(rs.getString("payment_method"));
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Record not found!!");
            }
               con.close();
               
        }
       
       catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
    }//GEN-LAST:event_search_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        new HospitalManagementSystem().show();
       dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void payment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_btnActionPerformed
         if(patient_id_txt.getText().equals(""))
            JOptionPane.showMessageDialog(null,"patient ID is mandetory");
        else if(patient_name_txt.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Patient name is mandetory");
        else if(service_textarea.getText().equals(""))
            JOptionPane.showMessageDialog(null,"service description is mandetory");
        else if(total_amount_txt.getText().equals(""))
            JOptionPane.showMessageDialog(null,"this field is mandetory");
        else if(payment_status_combo.getSelectedItem().toString().equals("select payment status"))
            JOptionPane.showMessageDialog(null,"please select payment status");
        else if(payment_method_combo.getSelectedItem().toString().equals("select payment method"))
            JOptionPane.showMessageDialog(null,"please select method of payment");
        else{
            payment_btn.setEnabled(true);
             payment_panel.setSelectedIndex(1);
        }
            
        
         if(payment_method_combo.getSelectedItem().toString().equals("UPI(unified payments interface)")){
              payment_panel.setSelectedIndex(2);
         }
         else
         {
             payment_panel.setSelectedIndex(1);
         }
             
         try{
              String sql1 = "insert into payment_table values (?,?,?,?,?,?,?)";
            pst = con2.prepareStatement(sql1);
            pst.setInt(1,Integer.parseInt(patient_id_txt.getText()));
            pst.setString(2, patient_name_txt.getText());
             pst.setString(3, service_textarea.getText());
             pst.setFloat(4, Float.valueOf(total_amount_txt.getText()));
              pst.setFloat(5, Float.valueOf(submitted_txt.getText()));
              
            String status;
            status = payment_status_combo.getSelectedItem().toString();
            pst.setString(6, status);
            String method;
            method = payment_method_combo.getSelectedItem().toString();
             pst.setString(7, method);
              pst.executeUpdate();
             con2.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_payment_btnActionPerformed

    private void robot_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robot_checkboxActionPerformed
        if(robot_checkbox.isSelected())
        pay_btn.setEnabled(true);
    }//GEN-LAST:event_robot_checkboxActionPerformed

    private void payment_process_home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_process_home_btnActionPerformed
         new HospitalManagementSystem().show();
       dispose();
    }//GEN-LAST:event_payment_process_home_btnActionPerformed

    private void payment_process_back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_process_back_btnActionPerformed
       payment_panel.setSelectedIndex(0);
    }//GEN-LAST:event_payment_process_back_btnActionPerformed

    private void payment_status_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_status_comboActionPerformed
       if(payment_status_combo.getSelectedItem().toString().equals("Paid")){
          payment_method_combo.setEnabled(false);
          payment_btn.setEnabled(false);
           //payment_panel.setEnabled(false);
      }
      else
      {
        payment_method_combo.setEnabled(true);
          payment_btn.setEnabled(true); 
           payment_panel.setEnabled(true);
      }
    }//GEN-LAST:event_payment_status_comboActionPerformed

    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed
         if(name_txt.getText().equals(""))
        JOptionPane.showMessageDialog(null,"name is mandetory");
        else if(card_number_txt.getText().equals(""))
        JOptionPane.showMessageDialog(null,"card number is mandetory");
        else if(security_code_txt.getText().equals(""))
        JOptionPane.showMessageDialog(null,"card number is mandetory");
        else if(day_txt.getText().equals("") && month_txt.getText().equals("") )
        JOptionPane.showMessageDialog(null," expiry date is mandetory");
        else if(phone_txt.getText().equals("") )
        JOptionPane.showMessageDialog(null," phone number is mandetory");
         else if(email_txt.getText().equals("") )
        JOptionPane.showMessageDialog(null," Email ID is mandetory");
        else
        JOptionPane.showMessageDialog(null,"Payment successful!!");
        
        
        
         try{
           String sql = "insert into payment_process_table values (?,?,?,?,?,?,?)" ;
           pst = con1.prepareStatement(sql);
           pst.setString(1,patient_name_txt.getText());
           pst.setString(2,card_number_txt.getText());
            pst.setInt(3, Integer.parseInt(security_code_txt.getText()));
            pst.setInt(4, Integer.parseInt(day_txt.getText()));
            pst.setInt(5, Integer.parseInt(month_txt.getText()));
           pst.setString(6,phone_txt.getText());
           pst.setString(7,email_txt.getText());
           
           pst.executeUpdate();
           con1.close();
          
       }
        catch(NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pay_btnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         try{
           String sql2 = "select * from payment_process_table where payor_name = ?" ;
           pst = searchcon.prepareStatement(sql2);
           pst.setString(1,name_txt.getText());
           rs = pst.executeQuery();
           
           if(rs.next()){
            card_number_txt.setText(rs.getString("card_number"));
           security_code_txt.setText(rs.getString("security_code"));
           day_txt.setText(rs.getString("day"));
           month_txt.setText(rs.getString("month"));
           phone_txt.setText(rs.getString("phone"));
           email_txt.setText(rs.getString("email"));
           }
          else
            {
                JOptionPane.showMessageDialog(null,"Record not found!!");
            }
               searchcon.close();
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFrame().setVisible(true);
            }
        });
         try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                
                 }
                catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e)
                {
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JRadioButton bhim_rbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField card_number_txt;
    private javax.swing.JTextField day_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JRadioButton gpay_rbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField month_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField patient_id_txt;
    private javax.swing.JTextField patient_name_txt;
    private javax.swing.JButton pay_btn;
    private javax.swing.JButton payment_btn;
    private javax.swing.JPanel payment_enroll_panel;
    private javax.swing.JComboBox<String> payment_method_combo;
    private javax.swing.JTabbedPane payment_panel;
    private javax.swing.JButton payment_process_back_btn;
    private javax.swing.JButton payment_process_home_btn;
    private javax.swing.JPanel payment_process_panel;
    private javax.swing.JComboBox<String> payment_status_combo;
    private javax.swing.JRadioButton paytm_rbtn;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JRadioButton phonepe_rbtn;
    private javax.swing.JButton qr_back_btn;
    private javax.swing.JButton qr_home_btn;
    private javax.swing.JLabel qr_label;
    private javax.swing.JButton qr_pay_btn;
    private javax.swing.JPanel qrscanner_panel;
    private javax.swing.JCheckBox robot_checkbox;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField security_code_txt;
    private javax.swing.JTextArea service_textarea;
    private javax.swing.JTextField submitted_txt;
    private javax.swing.JTextField total_amount_txt;
    // End of variables declaration//GEN-END:variables
}
